// Package gtk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gtk

import (
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// Displays a Gregorian calendar, one month at a time.
//
// &lt;picture&gt;
//
//	&lt;source srcset="calendar-dark.png" media="(prefers-color-scheme: dark)"&gt;
//	&lt;img alt="An example GtkCalendar" src="calendar.png"&gt;
//
// &lt;/picture&gt;
//
// A `GtkCalendar` can be created with [ctor@Gtk.Calendar.new].
//
// The selected date can be retrieved from a `GtkCalendar` using
// [method@Gtk.Calendar.get_date].
// It can be altered with [method@Gtk.Calendar.set_date].
//
// To place a visual marker on a particular day, use
// [method@Gtk.Calendar.mark_day] and to remove the marker,
// [method@Gtk.Calendar.unmark_day]. Alternative, all
// marks can be cleared with [method@Gtk.Calendar.clear_marks].
//
// Users should be aware that, although the Gregorian calendar is the
// legal calendar in most countries, it was adopted progressively
// between 1582 and 1929. Display before these dates is likely to be
// historically incorrect.
//
// # Shortcuts and Gestures
//
// `GtkCalendar` supports the following gestures:
//
// - Scrolling up or down will switch to the previous or next month.
// - Date strings can be dropped for setting the current day.
//
// # CSS nodes
//
// ```
// calendar.view
// ├── header
// │   ├── button
// │   ├── stack.month
// │   ├── button
// │   ├── button
// │   ├── label.year
// │   ╰── button
// ╰── grid
//
//	╰── label[.day-name][.week-number][.day-number][.other-month][.today]
//
// ```
//
// `GtkCalendar` has a main node with name calendar. It contains a subnode
// called header containing the widgets for switching between years and months.
//
// The grid subnode contains all day labels, including week numbers on the left
// (marked with the .week-number css class) and day names on top (marked with the
// .day-name css class).
//
// Day labels that belong to the previous or next month get the .other-month
// style class. The label of the current day get the .today style class.
//
// Marked day labels get the :selected state assigned.
type Calendar struct {
	Widget
}

var xCalendarGLibType func() types.GType

func CalendarGLibType() types.GType {
	return xCalendarGLibType()
}

func CalendarNewFromInternalPtr(ptr uintptr) *Calendar {
	cls := &Calendar{}
	cls.Ptr = ptr
	return cls
}

var xNewCalendar func() uintptr

// Creates a new calendar, with the current date being selected.
func NewCalendar() *Calendar {
	var cls *Calendar

	cret := xNewCalendar()

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &Calendar{}
	cls.Ptr = cret
	return cls
}

var xCalendarClearMarks func(uintptr)

// Remove all visual markers.
func (x *Calendar) ClearMarks() {

	xCalendarClearMarks(x.GoPointer())

}

var xCalendarGetDate func(uintptr) *glib.DateTime

// Returns a `GDateTime` representing the shown
// year, month and the selected day.
//
// The returned date is in the local time zone.
func (x *Calendar) GetDate() *glib.DateTime {

	cret := xCalendarGetDate(x.GoPointer())
	return cret
}

var xCalendarGetDay func(uintptr) int32

// Gets the day of the selected date.
func (x *Calendar) GetDay() int32 {

	cret := xCalendarGetDay(x.GoPointer())
	return cret
}

var xCalendarGetDayIsMarked func(uintptr, uint32) bool

// Returns if the @day of the @calendar is already marked.
func (x *Calendar) GetDayIsMarked(DayVar uint32) bool {

	cret := xCalendarGetDayIsMarked(x.GoPointer(), DayVar)
	return cret
}

var xCalendarGetMonth func(uintptr) int32

// Gets the month of the selected date.
func (x *Calendar) GetMonth() int32 {

	cret := xCalendarGetMonth(x.GoPointer())
	return cret
}

var xCalendarGetShowDayNames func(uintptr) bool

// Returns whether @self is currently showing the names
// of the week days.
//
// This is the value of the [property@Gtk.Calendar:show-day-names]
// property.
func (x *Calendar) GetShowDayNames() bool {

	cret := xCalendarGetShowDayNames(x.GoPointer())
	return cret
}

var xCalendarGetShowHeading func(uintptr) bool

// Returns whether @self is currently showing the heading.
//
// This is the value of the [property@Gtk.Calendar:show-heading]
// property.
func (x *Calendar) GetShowHeading() bool {

	cret := xCalendarGetShowHeading(x.GoPointer())
	return cret
}

var xCalendarGetShowWeekNumbers func(uintptr) bool

// Returns whether @self is showing week numbers right
// now.
//
// This is the value of the [property@Gtk.Calendar:show-week-numbers]
// property.
func (x *Calendar) GetShowWeekNumbers() bool {

	cret := xCalendarGetShowWeekNumbers(x.GoPointer())
	return cret
}

var xCalendarGetYear func(uintptr) int32

// Gets the year of the selected date.
func (x *Calendar) GetYear() int32 {

	cret := xCalendarGetYear(x.GoPointer())
	return cret
}

var xCalendarMarkDay func(uintptr, uint32)

// Places a visual marker on a particular day of the current month.
func (x *Calendar) MarkDay(DayVar uint32) {

	xCalendarMarkDay(x.GoPointer(), DayVar)

}

var xCalendarSelectDay func(uintptr, *glib.DateTime)

// Switches to @date's year and month and select its day.
func (x *Calendar) SelectDay(DateVar *glib.DateTime) {

	xCalendarSelectDay(x.GoPointer(), DateVar)

}

var xCalendarSetDate func(uintptr, *glib.DateTime)

// Switches to @date's year and month and selects its day.
func (x *Calendar) SetDate(DateVar *glib.DateTime) {

	xCalendarSetDate(x.GoPointer(), DateVar)

}

var xCalendarSetDay func(uintptr, int32)

// Sets the day for the selected date.
//
// The new date must be valid. For example, setting the day to 31 when the
// month is February will fail.
func (x *Calendar) SetDay(DayVar int32) {

	xCalendarSetDay(x.GoPointer(), DayVar)

}

var xCalendarSetMonth func(uintptr, int32)

// Sets the month for the selected date.
//
// The new date must be valid. For example, setting the month to 1 (February)
// when the day is 31 will fail.
func (x *Calendar) SetMonth(MonthVar int32) {

	xCalendarSetMonth(x.GoPointer(), MonthVar)

}

var xCalendarSetShowDayNames func(uintptr, bool)

// Sets whether the calendar shows day names.
func (x *Calendar) SetShowDayNames(ValueVar bool) {

	xCalendarSetShowDayNames(x.GoPointer(), ValueVar)

}

var xCalendarSetShowHeading func(uintptr, bool)

// Sets whether the calendar should show a heading.
//
// The heading contains the current year and month as well as
// buttons for changing both.
func (x *Calendar) SetShowHeading(ValueVar bool) {

	xCalendarSetShowHeading(x.GoPointer(), ValueVar)

}

var xCalendarSetShowWeekNumbers func(uintptr, bool)

// Sets whether week numbers are shown in the calendar.
func (x *Calendar) SetShowWeekNumbers(ValueVar bool) {

	xCalendarSetShowWeekNumbers(x.GoPointer(), ValueVar)

}

var xCalendarSetYear func(uintptr, int32)

// Sets the year for the selected date.
//
// The new date must be valid. For example, setting the year to 2023 when the
// date is February 29 will fail.
func (x *Calendar) SetYear(YearVar int32) {

	xCalendarSetYear(x.GoPointer(), YearVar)

}

var xCalendarUnmarkDay func(uintptr, uint32)

// Removes the visual marker from a particular day.
func (x *Calendar) UnmarkDay(DayVar uint32) {

	xCalendarUnmarkDay(x.GoPointer(), DayVar)

}

func (c *Calendar) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *Calendar) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyDate sets the "date" property.
// The selected date.
//
// This property gets initially set to the current date.
func (x *Calendar) SetPropertyDate(value uintptr) {
	var v gobject.Value
	v.Init(gobject.TypePointerVal)
	v.SetPointer(value)
	x.SetProperty("date", &v)
}

// GetPropertyDate gets the "date" property.
// The selected date.
//
// This property gets initially set to the current date.
func (x *Calendar) GetPropertyDate() uintptr {
	var v gobject.Value
	x.GetProperty("date", &v)
	return v.GetPointer()
}

// SetPropertyDay sets the "day" property.
// The selected day (as a number between 1 and 31).
func (x *Calendar) SetPropertyDay(value int32) {
	var v gobject.Value
	v.Init(gobject.TypeLongVal)
	v.SetLong(value)
	x.SetProperty("day", &v)
}

// GetPropertyDay gets the "day" property.
// The selected day (as a number between 1 and 31).
func (x *Calendar) GetPropertyDay() int32 {
	var v gobject.Value
	x.GetProperty("day", &v)
	return v.GetLong()
}

// SetPropertyMonth sets the "month" property.
// The selected month (as a number between 0 and 11).
//
// This property gets initially set to the current month.
func (x *Calendar) SetPropertyMonth(value int32) {
	var v gobject.Value
	v.Init(gobject.TypeLongVal)
	v.SetLong(value)
	x.SetProperty("month", &v)
}

// GetPropertyMonth gets the "month" property.
// The selected month (as a number between 0 and 11).
//
// This property gets initially set to the current month.
func (x *Calendar) GetPropertyMonth() int32 {
	var v gobject.Value
	x.GetProperty("month", &v)
	return v.GetLong()
}

// SetPropertyShowDayNames sets the "show-day-names" property.
// Determines whether day names are displayed.
func (x *Calendar) SetPropertyShowDayNames(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("show-day-names", &v)
}

// GetPropertyShowDayNames gets the "show-day-names" property.
// Determines whether day names are displayed.
func (x *Calendar) GetPropertyShowDayNames() bool {
	var v gobject.Value
	x.GetProperty("show-day-names", &v)
	return v.GetBoolean()
}

// SetPropertyShowHeading sets the "show-heading" property.
// Determines whether a heading is displayed.
func (x *Calendar) SetPropertyShowHeading(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("show-heading", &v)
}

// GetPropertyShowHeading gets the "show-heading" property.
// Determines whether a heading is displayed.
func (x *Calendar) GetPropertyShowHeading() bool {
	var v gobject.Value
	x.GetProperty("show-heading", &v)
	return v.GetBoolean()
}

// SetPropertyShowWeekNumbers sets the "show-week-numbers" property.
// Determines whether week numbers are displayed.
func (x *Calendar) SetPropertyShowWeekNumbers(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("show-week-numbers", &v)
}

// GetPropertyShowWeekNumbers gets the "show-week-numbers" property.
// Determines whether week numbers are displayed.
func (x *Calendar) GetPropertyShowWeekNumbers() bool {
	var v gobject.Value
	x.GetProperty("show-week-numbers", &v)
	return v.GetBoolean()
}

// SetPropertyYear sets the "year" property.
// The selected year.
//
// This property gets initially set to the current year.
func (x *Calendar) SetPropertyYear(value int32) {
	var v gobject.Value
	v.Init(gobject.TypeLongVal)
	v.SetLong(value)
	x.SetProperty("year", &v)
}

// GetPropertyYear gets the "year" property.
// The selected year.
//
// This property gets initially set to the current year.
func (x *Calendar) GetPropertyYear() int32 {
	var v gobject.Value
	x.GetProperty("year", &v)
	return v.GetLong()
}

// Emitted when the user selects a day.
func (x *Calendar) ConnectDaySelected(cb *func(Calendar)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "day-selected", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) {
		fa := Calendar{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "day-selected", cbRefPtr)
}

// Emitted when the user switches to the next month.
func (x *Calendar) ConnectNextMonth(cb *func(Calendar)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "next-month", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) {
		fa := Calendar{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "next-month", cbRefPtr)
}

// Emitted when user switches to the next year.
func (x *Calendar) ConnectNextYear(cb *func(Calendar)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "next-year", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) {
		fa := Calendar{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "next-year", cbRefPtr)
}

// Emitted when the user switches to the previous month.
func (x *Calendar) ConnectPrevMonth(cb *func(Calendar)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "prev-month", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) {
		fa := Calendar{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "prev-month", cbRefPtr)
}

// Emitted when user switches to the previous year.
func (x *Calendar) ConnectPrevYear(cb *func(Calendar)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "prev-year", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) {
		fa := Calendar{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "prev-year", cbRefPtr)
}

// Requests the user's screen reader to announce the given message.
//
// This kind of notification is useful for messages that
// either have only a visual representation or that are not
// exposed visually at all, e.g. a notification about a
// successful operation.
//
// Also, by using this API, you can ensure that the message
// does not interrupts the user's current screen reader output.
func (x *Calendar) Announce(MessageVar string, PriorityVar AccessibleAnnouncementPriority) {

	XGtkAccessibleAnnounce(x.GoPointer(), MessageVar, PriorityVar)

}

// Retrieves the accessible parent for an accessible object.
//
// This function returns `NULL` for top level widgets.
func (x *Calendar) GetAccessibleParent() *AccessibleBase {
	var cls *AccessibleBase

	cret := XGtkAccessibleGetAccessibleParent(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &AccessibleBase{}
	cls.Ptr = cret
	return cls
}

// Retrieves the accessible role of an accessible object.
func (x *Calendar) GetAccessibleRole() AccessibleRole {

	cret := XGtkAccessibleGetAccessibleRole(x.GoPointer())
	return cret
}

// Retrieves the implementation for the given accessible object.
func (x *Calendar) GetAtContext() *ATContext {
	var cls *ATContext

	cret := XGtkAccessibleGetAtContext(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &ATContext{}
	cls.Ptr = cret
	return cls
}

// Queries the coordinates and dimensions of this accessible
//
// This functionality can be overridden by `GtkAccessible`
// implementations, e.g. to get the bounds from an ignored
// child widget.
func (x *Calendar) GetBounds(XVar *int32, YVar *int32, WidthVar *int32, HeightVar *int32) bool {

	cret := XGtkAccessibleGetBounds(x.GoPointer(), XVar, YVar, WidthVar, HeightVar)
	return cret
}

// Retrieves the first accessible child of an accessible object.
func (x *Calendar) GetFirstAccessibleChild() *AccessibleBase {
	var cls *AccessibleBase

	cret := XGtkAccessibleGetFirstAccessibleChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &AccessibleBase{}
	cls.Ptr = cret
	return cls
}

// Retrieves the next accessible sibling of an accessible object
func (x *Calendar) GetNextAccessibleSibling() *AccessibleBase {
	var cls *AccessibleBase

	cret := XGtkAccessibleGetNextAccessibleSibling(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &AccessibleBase{}
	cls.Ptr = cret
	return cls
}

// Queries a platform state, such as focus.
//
// This functionality can be overridden by `GtkAccessible`
// implementations, e.g. to get platform state from an ignored
// child widget, as is the case for `GtkText` wrappers.
func (x *Calendar) GetPlatformState(StateVar AccessiblePlatformState) bool {

	cret := XGtkAccessibleGetPlatformState(x.GoPointer(), StateVar)
	return cret
}

// Resets the accessible property to its default value.
func (x *Calendar) ResetProperty(PropertyVar AccessibleProperty) {

	XGtkAccessibleResetProperty(x.GoPointer(), PropertyVar)

}

// Resets the accessible relation to its default value.
func (x *Calendar) ResetRelation(RelationVar AccessibleRelation) {

	XGtkAccessibleResetRelation(x.GoPointer(), RelationVar)

}

// Resets the accessible state to its default value.
func (x *Calendar) ResetState(StateVar AccessibleState) {

	XGtkAccessibleResetState(x.GoPointer(), StateVar)

}

// Sets the parent and sibling of an accessible object.
//
// This function is meant to be used by accessible implementations that are
// not part of the widget hierarchy, and but act as a logical bridge between
// widgets. For instance, if a widget creates an object that holds metadata
// for each child, and you want that object to implement the `GtkAccessible`
// interface, you will use this function to ensure that the parent of each
// child widget is the metadata object, and the parent of each metadata
// object is the container widget.
func (x *Calendar) SetAccessibleParent(ParentVar Accessible, NextSiblingVar Accessible) {

	XGtkAccessibleSetAccessibleParent(x.GoPointer(), ParentVar.GoPointer(), NextSiblingVar.GoPointer())

}

// Updates the next accessible sibling.
//
// That might be useful when a new child of a custom accessible
// is created, and it needs to be linked to a previous child.
func (x *Calendar) UpdateNextAccessibleSibling(NewSiblingVar Accessible) {

	XGtkAccessibleUpdateNextAccessibleSibling(x.GoPointer(), NewSiblingVar.GoPointer())

}

// Informs ATs that the platform state has changed.
//
// This function should be used by `GtkAccessible` implementations that
// have a platform state but are not widgets. Widgets handle platform
// states automatically.
func (x *Calendar) UpdatePlatformState(StateVar AccessiblePlatformState) {

	XGtkAccessibleUpdatePlatformState(x.GoPointer(), StateVar)

}

// Updates a list of accessible properties.
//
// See the [enum@Gtk.AccessibleProperty] documentation for the
// value types of accessible properties.
//
// This function should be called by `GtkWidget` types whenever
// an accessible property change must be communicated to assistive
// technologies.
//
// Example:
// ```c
// value = gtk_adjustment_get_value (adjustment);
// gtk_accessible_update_property (GTK_ACCESSIBLE (spin_button),
//
//	GTK_ACCESSIBLE_PROPERTY_VALUE_NOW, value,
//	-1);
//
// ```
func (x *Calendar) UpdateProperty(FirstPropertyVar AccessibleProperty, varArgs ...interface{}) {

	XGtkAccessibleUpdateProperty(x.GoPointer(), FirstPropertyVar, varArgs...)

}

// Updates an array of accessible properties.
//
// This function should be called by `GtkWidget` types whenever an accessible
// property change must be communicated to assistive technologies.
//
// This function is meant to be used by language bindings.
func (x *Calendar) UpdatePropertyValue(NPropertiesVar int32, PropertiesVar []AccessibleProperty, ValuesVar []gobject.Value) {

	XGtkAccessibleUpdatePropertyValue(x.GoPointer(), NPropertiesVar, PropertiesVar, ValuesVar)

}

// Updates a list of accessible relations.
//
// This function should be called by `GtkWidget` types whenever an accessible
// relation change must be communicated to assistive technologies.
//
// If the [enum@Gtk.AccessibleRelation] requires a list of references,
// you should pass each reference individually, followed by `NULL`, e.g.
//
// ```c
// gtk_accessible_update_relation (accessible,
//
//	GTK_ACCESSIBLE_RELATION_CONTROLS,
//	  ref1, NULL,
//	GTK_ACCESSIBLE_RELATION_LABELLED_BY,
//	  ref1, ref2, ref3, NULL,
//	-1);
//
// ```
func (x *Calendar) UpdateRelation(FirstRelationVar AccessibleRelation, varArgs ...interface{}) {

	XGtkAccessibleUpdateRelation(x.GoPointer(), FirstRelationVar, varArgs...)

}

// Updates an array of accessible relations.
//
// This function should be called by `GtkWidget` types whenever an accessible
// relation change must be communicated to assistive technologies.
//
// This function is meant to be used by language bindings.
func (x *Calendar) UpdateRelationValue(NRelationsVar int32, RelationsVar []AccessibleRelation, ValuesVar []gobject.Value) {

	XGtkAccessibleUpdateRelationValue(x.GoPointer(), NRelationsVar, RelationsVar, ValuesVar)

}

// Updates a list of accessible states.
//
// See the [enum@Gtk.AccessibleState] documentation for the
// value types of accessible states.
//
// This function should be called by `GtkWidget` types whenever
// an accessible state change must be communicated to assistive
// technologies.
//
// Example:
//
// ```c
// value = GTK_ACCESSIBLE_TRISTATE_MIXED;
// gtk_accessible_update_state (GTK_ACCESSIBLE (check_button),
//
//	GTK_ACCESSIBLE_STATE_CHECKED, value,
//	-1);
//
// ```
func (x *Calendar) UpdateState(FirstStateVar AccessibleState, varArgs ...interface{}) {

	XGtkAccessibleUpdateState(x.GoPointer(), FirstStateVar, varArgs...)

}

// Updates an array of accessible states.
//
// This function should be called by `GtkWidget` types whenever an accessible
// state change must be communicated to assistive technologies.
//
// This function is meant to be used by language bindings.
func (x *Calendar) UpdateStateValue(NStatesVar int32, StatesVar []AccessibleState, ValuesVar []gobject.Value) {

	XGtkAccessibleUpdateStateValue(x.GoPointer(), NStatesVar, StatesVar, ValuesVar)

}

// Gets the ID of the @buildable object.
//
// `GtkBuilder` sets the name based on the ID attribute
// of the `&lt;object&gt;` tag used to construct the @buildable.
func (x *Calendar) GetBuildableId() string {

	cret := XGtkBuildableGetBuildableId(x.GoPointer())
	return cret
}

func init() {
	core.SetPackageName("GTK", "gtk4")
	core.SetSharedLibraries("GTK", []string{"libgtk-4.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GTK") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xCalendarGLibType, libs, "gtk_calendar_get_type")

	core.PuregoSafeRegister(&xNewCalendar, libs, "gtk_calendar_new")

	core.PuregoSafeRegister(&xCalendarClearMarks, libs, "gtk_calendar_clear_marks")
	core.PuregoSafeRegister(&xCalendarGetDate, libs, "gtk_calendar_get_date")
	core.PuregoSafeRegister(&xCalendarGetDay, libs, "gtk_calendar_get_day")
	core.PuregoSafeRegister(&xCalendarGetDayIsMarked, libs, "gtk_calendar_get_day_is_marked")
	core.PuregoSafeRegister(&xCalendarGetMonth, libs, "gtk_calendar_get_month")
	core.PuregoSafeRegister(&xCalendarGetShowDayNames, libs, "gtk_calendar_get_show_day_names")
	core.PuregoSafeRegister(&xCalendarGetShowHeading, libs, "gtk_calendar_get_show_heading")
	core.PuregoSafeRegister(&xCalendarGetShowWeekNumbers, libs, "gtk_calendar_get_show_week_numbers")
	core.PuregoSafeRegister(&xCalendarGetYear, libs, "gtk_calendar_get_year")
	core.PuregoSafeRegister(&xCalendarMarkDay, libs, "gtk_calendar_mark_day")
	core.PuregoSafeRegister(&xCalendarSelectDay, libs, "gtk_calendar_select_day")
	core.PuregoSafeRegister(&xCalendarSetDate, libs, "gtk_calendar_set_date")
	core.PuregoSafeRegister(&xCalendarSetDay, libs, "gtk_calendar_set_day")
	core.PuregoSafeRegister(&xCalendarSetMonth, libs, "gtk_calendar_set_month")
	core.PuregoSafeRegister(&xCalendarSetShowDayNames, libs, "gtk_calendar_set_show_day_names")
	core.PuregoSafeRegister(&xCalendarSetShowHeading, libs, "gtk_calendar_set_show_heading")
	core.PuregoSafeRegister(&xCalendarSetShowWeekNumbers, libs, "gtk_calendar_set_show_week_numbers")
	core.PuregoSafeRegister(&xCalendarSetYear, libs, "gtk_calendar_set_year")
	core.PuregoSafeRegister(&xCalendarUnmarkDay, libs, "gtk_calendar_unmark_day")

}
