// Package gobject was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gobject

// A #GValueArray contains an array of #GValue elements.
type ValueArray struct {
	NValues uint

	Values *Value

	NPrealloced uint
}
