// Package webkit was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package webkit

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
)

var xUriForDisplay func(string) string

// Use this function to format a URI for display.
//
// The URIs used internally by
// WebKit may contain percent-encoded characters or Punycode, which are not
// generally suitable to display to users. This function provides protection
// against IDN homograph attacks, so in some cases the host part of the returned
// URI may be in Punycode if the safety check fails.
func UriForDisplay(UriVar string) string {

	cret := xUriForDisplay(UriVar)
	return cret
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("WEBKIT") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xUriForDisplay, libs, "webkit_uri_for_display")

}
