// Package webkit was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// Describes a web engine feature that may be toggled at runtime.
//
// The WebKit web engine includes a set of features which may be toggled
// programmatically, each one represented by a #WebKitFeature that provides
// information about it:
//
//   - A unique “identifier”: [method@Feature.get_identifier].
//   - A “default value”, which indicates whether the option is enabled
//     automatically: [method@Feature.get_default_value].
//   - Its “status”, which determines whether it should be considered
//     user-settable and its development stage (see [enum@FeatureStatus]
//     for details): [method@Feature.get_status].
//   - A category, which may be used to group features together:
//     [method@Feature.get_category].
//   - An optional short “name” which can be presented to an user:
//     [method@Feature.get_name].
//   - An optional longer “detailed” description:
//     [method@Feature.get_details].
//
// The lists of available features can be obtained with
// [func@Settings.get_all_features], [func@Settings.get_experimental_features],
// and [func@Settings.get_development_features]). As a rule of thumb,
// applications which may want to allow users (i.e. web developers) to test
// WebKit features should use the list of experimental features. Additionally,
// applications might want to expose development features *when targeting
// technically inclined users* for early testing of in-development features
// (i.e. in “technology preview” or “canary” builds).
//
// Applications **must not** expose the list of all features to end users
// because they often lack descriptions and control parts of the web engine
// which are either intended to be used during development of WebKit itself,
// or in specific scenarios to tweak how WebKit integrates with the
// application.
type Feature struct {
	_ structs.HostLayout
}

var xFeatureGLibType func() types.GType

func FeatureGLibType() types.GType {
	return xFeatureGLibType()
}

func (x *Feature) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xFeatureGetCategory func(uintptr) string

// Gets the category of the feature.
//
// Applications which include user interface to toggle features may want
// to use the category to group related features together.
func (x *Feature) GetCategory() string {

	cret := xFeatureGetCategory(x.GoPointer())
	return cret
}

var xFeatureGetDefaultValue func(uintptr) bool

// Gets whether the feature is enabled by default.
//
// The default value may be used by applications which include user interface
// to toggle features to restore its settings to their defaults. Note that
// whether a feature is actually enabled must be checked with
// [method@Settings.get_feature_enabled].
func (x *Feature) GetDefaultValue() bool {

	cret := xFeatureGetDefaultValue(x.GoPointer())
	return cret
}

var xFeatureGetDetails func(uintptr) string

// Gets a description for the @feature.
//
// The detailed description should be considered an additional clarification
// on the purpose of the feature, to be used as complementary aid to be
// displayed along the feature name returned by [method@Feature.get_name].
// The returned string is suitable to be displayed to end users, but it
// should not be relied upon being localized.
//
// Note that some *features may not* have a detailed description, and @NULL
// is returned in this case.
func (x *Feature) GetDetails() string {

	cret := xFeatureGetDetails(x.GoPointer())
	return cret
}

var xFeatureGetIdentifier func(uintptr) string

// Gets a string that uniquely identifies the @feature.
func (x *Feature) GetIdentifier() string {

	cret := xFeatureGetIdentifier(x.GoPointer())
	return cret
}

var xFeatureGetName func(uintptr) string

// Gets a short name for the @feature.
//
// The returned string is suitable to be displayed to end users, but it
// should not be relied upon being localized.
//
// Note that some *features may not* have a short name, and @NULL
// is returned in this case.
func (x *Feature) GetName() string {

	cret := xFeatureGetName(x.GoPointer())
	return cret
}

var xFeatureGetStatus func(uintptr) FeatureStatus

// Gets the status of the feature.
func (x *Feature) GetStatus() FeatureStatus {

	cret := xFeatureGetStatus(x.GoPointer())
	return cret
}

var xFeatureRef func(uintptr) *Feature

// Atomically acquires a reference on the given @feature.
//
// This function is MT-safe and may be called from any thread.
func (x *Feature) Ref() *Feature {

	cret := xFeatureRef(x.GoPointer())
	return cret
}

var xFeatureUnref func(uintptr)

// Atomically releases a reference on the given @feature.
//
// If the reference was the last, the resources associated to the
// @feature are freed. This function is MT-safe and may be called from
// any thread.
func (x *Feature) Unref() {

	xFeatureUnref(x.GoPointer())

}

// Contains a set of toggle-able web engine features.
//
// The list supports passing around a set of [struct@Feature] objects and
// iterating over them:
//
// ```c
// g_autoptr(WebKitFeatureList) list = webkit_settings_get_experimental_features();
//
//	for (gsize i = 0; i &lt; webkit_feature_list_get_length(list): i++) {
//	    WebKitFeature *feature = webkit_feature_list_get(list, i);
//	    // Do something with "feature".
//	}
//
// ```
//
// Lists of features can be obtained with
// [func@Settings.get_experimental_features],
// [func@Settings.get_development_features], and
// [func@Settings.get_all_features].
type FeatureList struct {
	_ structs.HostLayout
}

var xFeatureListGLibType func() types.GType

func FeatureListGLibType() types.GType {
	return xFeatureListGLibType()
}

func (x *FeatureList) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xFeatureListGet func(uintptr, uint) *Feature

// Gets a feature given its index.
func (x *FeatureList) Get(IndexVar uint) *Feature {

	cret := xFeatureListGet(x.GoPointer(), IndexVar)
	return cret
}

var xFeatureListGetLength func(uintptr) uint

// Gets the number of elements in the feature list.
func (x *FeatureList) GetLength() uint {

	cret := xFeatureListGetLength(x.GoPointer())
	return cret
}

var xFeatureListRef func(uintptr) *FeatureList

// Atomically acquires a reference on the given @feature_list.
//
// This function is MT-safe and may be called from any thread.
func (x *FeatureList) Ref() *FeatureList {

	cret := xFeatureListRef(x.GoPointer())
	return cret
}

var xFeatureListUnref func(uintptr)

// Atomically releases a reference on the given @feature_list.
//
// If the reference was the last, the resources associated to the
// @feature_list are freed. This function is MT-safe and may be called
// from any thread.
func (x *FeatureList) Unref() {

	xFeatureListUnref(x.GoPointer())

}

// Describes the status of a [struct@WebKitFeature].
//
// The status for a given feature can be obtained with
// [id@webkit_feature_get_status].
type FeatureStatus int

var xFeatureStatusGLibType func() types.GType

func FeatureStatusGLibType() types.GType {
	return xFeatureStatusGLibType()
}

const (

	// Feature that adjust behaviour for
	//   specific application needs. The feature is not part of a Web platform
	//   feature, not a mature feature intended to be always on.
	FeatureStatusEmbedderValue FeatureStatus = 0
	// Feature in development. The feature
	//   may be unfinished, and there are no guarantees about its safety and
	//   stability.
	FeatureStatusUnstableValue FeatureStatus = 1
	// Feature for debugging the WebKit engine.
	//   The feature is not generally useful for user or web developers, and
	//   always disabled by default.
	FeatureStatusInternalValue FeatureStatus = 2
	// Feature for web developers. The feature
	//   is not generally useful for end users, and always disabled by default.
	FeatureStatusDeveloperValue FeatureStatus = 3
	// Feature in active development and
	//   complete enough for testing. The feature may not be yet ready to
	//   ship and is disabled by default.
	FeatureStatusTestableValue FeatureStatus = 4
	// Feature ready to be tested by users.
	//   The feature is disabled by default, but may be enabled by applications
	//   automatically e.g. in their “technology preview” or “beta” versions.
	FeatureStatusPreviewValue FeatureStatus = 5
	// Feature ready for general use. The
	//   feature is enabled by default, but it may still be toggled to support
	//   debugging and testing.
	FeatureStatusStableValue FeatureStatus = 6
	// Feature in general use. The feature is
	//   always enabled and in general there should be no user-facing interface
	//   to toggle it.
	FeatureStatusMatureValue FeatureStatus = 7
)

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("WEBKIT") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xFeatureStatusGLibType, libs, "webkit_feature_status_get_type")

	core.PuregoSafeRegister(&xFeatureGLibType, libs, "webkit_feature_get_type")

	core.PuregoSafeRegister(&xFeatureGetCategory, libs, "webkit_feature_get_category")
	core.PuregoSafeRegister(&xFeatureGetDefaultValue, libs, "webkit_feature_get_default_value")
	core.PuregoSafeRegister(&xFeatureGetDetails, libs, "webkit_feature_get_details")
	core.PuregoSafeRegister(&xFeatureGetIdentifier, libs, "webkit_feature_get_identifier")
	core.PuregoSafeRegister(&xFeatureGetName, libs, "webkit_feature_get_name")
	core.PuregoSafeRegister(&xFeatureGetStatus, libs, "webkit_feature_get_status")
	core.PuregoSafeRegister(&xFeatureRef, libs, "webkit_feature_ref")
	core.PuregoSafeRegister(&xFeatureUnref, libs, "webkit_feature_unref")

	core.PuregoSafeRegister(&xFeatureListGLibType, libs, "webkit_feature_list_get_type")

	core.PuregoSafeRegister(&xFeatureListGet, libs, "webkit_feature_list_get")
	core.PuregoSafeRegister(&xFeatureListGetLength, libs, "webkit_feature_list_get_length")
	core.PuregoSafeRegister(&xFeatureListRef, libs, "webkit_feature_list_ref")
	core.PuregoSafeRegister(&xFeatureListUnref, libs, "webkit_feature_list_unref")

}
