// Package webkit was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type GeolocationManagerClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *GeolocationManagerClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// An opaque struct to provide position updates to a #WebKitGeolocationManager.
//
// WebKitGeolocationPosition is an opaque struct used to provide position updates to a
// #WebKitGeolocationManager using webkit_geolocation_manager_update_position().
type GeolocationPosition struct {
	_ structs.HostLayout
}

var xGeolocationPositionGLibType func() types.GType

func GeolocationPositionGLibType() types.GType {
	return xGeolocationPositionGLibType()
}

func (x *GeolocationPosition) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xNewGeolocationPosition func(float64, float64, float64) *GeolocationPosition

// Create a new #WebKitGeolocationPosition.
func NewGeolocationPosition(LatitudeVar float64, LongitudeVar float64, AccuracyVar float64) *GeolocationPosition {

	cret := xNewGeolocationPosition(LatitudeVar, LongitudeVar, AccuracyVar)
	return cret
}

var xGeolocationPositionCopy func(uintptr) *GeolocationPosition

// Make a copy of the #WebKitGeolocationPosition.
func (x *GeolocationPosition) Copy() *GeolocationPosition {

	cret := xGeolocationPositionCopy(x.GoPointer())
	return cret
}

var xGeolocationPositionFree func(uintptr)

// Free the #WebKitGeolocationPosition
func (x *GeolocationPosition) Free() {

	xGeolocationPositionFree(x.GoPointer())

}

var xGeolocationPositionSetAltitude func(uintptr, float64)

// Set the @position altitude.
func (x *GeolocationPosition) SetAltitude(AltitudeVar float64) {

	xGeolocationPositionSetAltitude(x.GoPointer(), AltitudeVar)

}

var xGeolocationPositionSetAltitudeAccuracy func(uintptr, float64)

// Set the accuracy of @position altitude.
func (x *GeolocationPosition) SetAltitudeAccuracy(AltitudeAccuracyVar float64) {

	xGeolocationPositionSetAltitudeAccuracy(x.GoPointer(), AltitudeAccuracyVar)

}

var xGeolocationPositionSetHeading func(uintptr, float64)

// Set the @position heading.
//
// Set the @position heading, as a positive angle between the direction of movement and the North
// direction, in clockwise direction.
func (x *GeolocationPosition) SetHeading(HeadingVar float64) {

	xGeolocationPositionSetHeading(x.GoPointer(), HeadingVar)

}

var xGeolocationPositionSetSpeed func(uintptr, float64)

// Set the @position speed.
func (x *GeolocationPosition) SetSpeed(SpeedVar float64) {

	xGeolocationPositionSetSpeed(x.GoPointer(), SpeedVar)

}

var xGeolocationPositionSetTimestamp func(uintptr, uint64)

// Set the @position timestamp.
//
// By default it's the time when the @position was created.
func (x *GeolocationPosition) SetTimestamp(TimestampVar uint64) {

	xGeolocationPositionSetTimestamp(x.GoPointer(), TimestampVar)

}

// Geolocation manager.
//
// WebKitGeolocationManager provides API to get the geographical position of the user.
// Once a #WebKitGeolocationPermissionRequest is allowed, when WebKit needs to know the
// user location #WebKitGeolocationManager::start signal is emitted. If the signal is handled
// and returns %TRUE, the application is responsible for providing the position every time it's
// updated by calling webkit_geolocation_manager_update_position(). The signal #WebKitGeolocationManager::stop
// will be emitted when location updates are no longer needed.
type GeolocationManager struct {
	gobject.Object
}

var xGeolocationManagerGLibType func() types.GType

func GeolocationManagerGLibType() types.GType {
	return xGeolocationManagerGLibType()
}

func GeolocationManagerNewFromInternalPtr(ptr uintptr) *GeolocationManager {
	cls := &GeolocationManager{}
	cls.Ptr = ptr
	return cls
}

var xGeolocationManagerFailed func(uintptr, string)

// Notify @manager that determining the position failed.
func (x *GeolocationManager) Failed(ErrorMessageVar string) {

	xGeolocationManagerFailed(x.GoPointer(), ErrorMessageVar)

}

var xGeolocationManagerGetEnableHighAccuracy func(uintptr) bool

// Get whether high accuracy is enabled.
func (x *GeolocationManager) GetEnableHighAccuracy() bool {

	cret := xGeolocationManagerGetEnableHighAccuracy(x.GoPointer())
	return cret
}

var xGeolocationManagerUpdatePosition func(uintptr, *GeolocationPosition)

// Notify @manager that position has been updated to @position.
func (x *GeolocationManager) UpdatePosition(PositionVar *GeolocationPosition) {

	xGeolocationManagerUpdatePosition(x.GoPointer(), PositionVar)

}

func (c *GeolocationManager) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *GeolocationManager) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// GetPropertyEnableHighAccuracy gets the "enable-high-accuracy" property.
// Whether high accuracy is enabled. This is a read-only property that will be
// set to %TRUE when a #WebKitGeolocationManager needs to get accurate position updates.
// You can connect to notify::enable-high-accuracy signal to monitor it.
func (x *GeolocationManager) GetPropertyEnableHighAccuracy() bool {
	var v gobject.Value
	x.GetProperty("enable-high-accuracy", &v)
	return v.GetBoolean()
}

// The signal is emitted to notify that @manager needs to start receiving
// position updates. After this signal is emitted the user should provide
// the updates using webkit_geolocation_manager_update_position() every time
// the position changes, or use webkit_geolocation_manager_failed() in case
// it isn't possible to determine the current position.
//
// If the signal is not handled, WebKit will try to determine the position
// using GeoClue if available.
func (x *GeolocationManager) ConnectStart(cb *func(GeolocationManager) bool) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "start", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) bool {
		fa := GeolocationManager{}
		fa.Ptr = clsPtr
		cbFn := *cb

		return cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "start", cbRefPtr)
}

// The signal is emitted to notify that @manager doesn't need to receive
// position updates anymore.
func (x *GeolocationManager) ConnectStop(cb *func(GeolocationManager)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "stop", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) {
		fa := GeolocationManager{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "stop", cbRefPtr)
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("WEBKIT") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xGeolocationPositionGLibType, libs, "webkit_geolocation_position_get_type")

	core.PuregoSafeRegister(&xNewGeolocationPosition, libs, "webkit_geolocation_position_new")

	core.PuregoSafeRegister(&xGeolocationPositionCopy, libs, "webkit_geolocation_position_copy")
	core.PuregoSafeRegister(&xGeolocationPositionFree, libs, "webkit_geolocation_position_free")
	core.PuregoSafeRegister(&xGeolocationPositionSetAltitude, libs, "webkit_geolocation_position_set_altitude")
	core.PuregoSafeRegister(&xGeolocationPositionSetAltitudeAccuracy, libs, "webkit_geolocation_position_set_altitude_accuracy")
	core.PuregoSafeRegister(&xGeolocationPositionSetHeading, libs, "webkit_geolocation_position_set_heading")
	core.PuregoSafeRegister(&xGeolocationPositionSetSpeed, libs, "webkit_geolocation_position_set_speed")
	core.PuregoSafeRegister(&xGeolocationPositionSetTimestamp, libs, "webkit_geolocation_position_set_timestamp")

	core.PuregoSafeRegister(&xGeolocationManagerGLibType, libs, "webkit_geolocation_manager_get_type")

	core.PuregoSafeRegister(&xGeolocationManagerFailed, libs, "webkit_geolocation_manager_failed")
	core.PuregoSafeRegister(&xGeolocationManagerGetEnableHighAccuracy, libs, "webkit_geolocation_manager_get_enable_high_accuracy")
	core.PuregoSafeRegister(&xGeolocationManagerUpdatePosition, libs, "webkit_geolocation_manager_update_position")

	// Manually register types since they aren't being automatically registered when
	// the library is loaded
	// See https://bugs.webkit.org/show_bug.cgi?id=175937
	GeolocationManagerGLibType()
}
